# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 415961c6f865a3d360eec3ccf62ec4bc6f837b4bd80eac5bce74abf57d9f438d6db0b661747af4d7978ecd4bc02affb5712b5480b6edd7bb34380c7e37c51be6

test:
  secret_key_base: e28f6dda5d634bddaf6ee69099ff14eb1bfc6d8621099dace4aadeb63eb1f2169ebfb763fdcb056b3921b5978e7e5e776a0388afceb982811e6aef34fad8a3ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
